name: Create Release Archive

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'source'
          
      - name: Exclude directory
        run: |
          mv source/.github/workflows source/.github/workflows_tmp
        shell: bash

      - name: Create archive
        run: |
          cd source
          mkdir CSZSitemap
          cp -r * CSZSitemap/
          zip -r CSZSitemap.zip CSZSitemap
        shell: bash

      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: Release Archive
          path: source/CSZSitemap.zip

      - name: Restore directory
        run: |
          mv source/.github/workflows_tmp source/.github/workflows
        shell: bash